inp_string = input()
print(inp_string[2])
print(inp_string[-2])
print(inp_string[:5])
print(inp_string[:len(inp_string) - 2])
print(inp_string[::2])
print(inp_string[1::2])
print(inp_string[::-1])
print(inp_string[::-2])
